replacements = {
    '/* Star 状态四按钮（不含装修）使用像素精灵皮肤 */': '/* Star State four buttons (excluding decoration) use pixel sprite skin */',
    '写你的风格主题（严格保持原始房间结构，只改变视觉风格）': 'Write your style theme (strictly maintain the original room structure, only change the visual style)',
    '例如：像素风赛博东京夜景，霓虹灯、雨夜地面反光、蓝紫主色': 'For example: pixel style cyber Tokyo night view, neon lights, rainy night ground reflections, blue-purple main color',
    'Default password:1234（可随时让我帮你改，建议改成强密码）': 'Default password:1234 (You can ask me to change it at any time, it is recommended to change to a strong password)',
    '可见性：点击条目右侧眼睛按钮切换该资产显示': 'Visibility: Click the eye button on the right side of the item to toggle the visibility of the asset',
    "👁 サイドバーを隠す": "👁 Hide Sidebar",
    "👁 サイドバーをexpress": "👁 Show Sidebar",
    "デフォルトへ戻す": "Reset to Default",
    "forwardのversionへ戻す": "Restore Previous Version",
    "📦 leadっcrossし": "📦 Move",
    "🐚 実家に戻る": "🐚 Return Home",
    "↩️ ひとつforwardへ": "↩️ One Step Forward",
    "⭐ このHomeをsave": "⭐ Save This Home",
    "🤝 intermediary": "🤝 Broker",
    "🪚 self-dividedでdecoration": "🪚 DIY Decoration",
    "intermediaryにappointせる": "Appoint Broker",
    "🏠 saveしたHome": "🏠 Saved Homes",
    "まだsaveがありません. Firstに「⭐ このHomeをsave\"をchargeしてください.": "No saves yet. Please save this home first.",
    "nowのマップにApplicable": "Apply to Current Map",
    "✅ nowのマップをsaveしました": "✅ Current Map Saved",
    "✅ saveしたHomeをApplicableしました": "✅ Saved Home Applied",
    "アセット検SO(desk / sofa / star)": "Search Asset (desk / sofa / star)",
    "recognizeみ込み済み": "Loaded",
    "Completeアセット": "All Assets",
    "HuggingClaw のHomeをrecognizeみ込みmiddle...": "Loading HuggingClaw Home...",
    "non-expression": "Hidden",
    "アセットrecognizeみ込み": "Asset Loading",
    "シーンobtain": "Scene Capture",
    "アセットrecognizeみ込みFail. renewしてTry againしてください": "Asset Loading Failed. Please Wait and Try Again.",
    "stateDetailIdle: 'standby', stateDetailWriting: 'Document sorting', stateDetailResearching: 'intelligence search', stateDetailExecuting: 'タスク実行', stateDetailSyncing: 'same periodバックアップ', stateDetailError: 'エラー発生',": "stateDetailIdle: 'standby', stateDetailWriting: 'Document sorting', stateDetailResearching: 'intelligence search', stateDetailExecuting: 'task execution', stateDetailSyncing: 'same period backup', stateDetailError: 'error occurred',",
    "stateLabelIdle: 'standby', stateLabelWriting: 'Document sorting', stateLabelResearching: 'intelligence search', stateLabelExecuting: 'タスク実行', stateLabelSyncing: 'same periodバックアップ', stateLabelError: 'エラー発生',": "stateLabelIdle: 'standby', stateLabelWriting: 'Document sorting', stateLabelResearching: 'intelligence search', stateLabelExecuting: 'task execution', stateLabelSyncing: 'same period backup', stateLabelError: 'error occurred',",
    "语言切换后立即重绘资产侧栏，确保易懂名同步更新": "Immediately redraw the asset sidebar after language switch to ensure friendly names are synced.",
    "语言切换后同步刷新已选资产的指导文案（上传区小字三语联动）": "Synchronously refresh the instruction text of selected assets after language switch.",
    "Keep on desktop FIT；for mobile phone use RESIZE, and do it by height in the camera fit(Can be landscaped pan)": "Keep on desktop FIT; for mobile phone use RESIZE, and fit by height in camera (horizontal panning supported)",
    "During the same period: todayをクラウドにseal.": "Sync: Seal today in cloud.",
    "バックアップはceremonyじゃなくPeace of mind.": "Backup is Peace of mind, not ceremony.",
    "Bookき込みmiddle…power supplyオフCaptivity.": "Writing in progress... Do not turn off power.",
    "Changeはタイムスタンプへ.": "Save changes to timestamp.",
    "クラウドEntire column:カチッ.": "Cloud synchronized.",
    "The same period is overまでtouchらないで.": "Do not touch until sync completes.",
    "futureのself-dividedをDisasterからsaveう.": "Save future self from disaster.",
    "バックアップoneつ, regret oneつreduceる.": "One backup reduces one regret.",
    "Alert:まずfallちWithいて.": "Alert: Stay calm.",
    "バグの気matchをfeelじる.": "Feel the presence of bugs.",
    "ReappearしてからCorrectionへ.": "Reproduce then correct.",
    "ログをください, human languageにします.": "Give me logs, I will parse to human language.",
    "エラーはenemyではなくhandがかり.": "Errors are clues, not enemies.",
    "まずInfluence rangeをtrappedう.": "Find the blast radius first.",
    "Stop bleedingしてからOperation.": "Stop bleeding before operation.",
    "nowすぐroot causeをTracking.": "Tracking root cause now.",
    "A real man,よくあるcase.": "A common case.",
    "alertモード:problemをVisualizationする.": "Alert Mode: Visualizing the problem.",
    "The protagonist's standby animation table. please keep 256×256 分帧与网格布局一致，否则待机动作会错帧。": "The protagonist's standby animation table. please keep 256x256 framing layout consistent, otherwise standby animation will skip frames.",
    "Sofa shadow layer.建议与沙发主体同坐标叠放，增强贴地感。": "Sofa shadow layer. Suggest stacking at same coordinates as sofa body to enhance grounding.",
    "Notes panel base image.建议留出文字阅读区域，降低高频纹理，避免信息难读。": "Notes panel base image. Suggest leaving text reading area, lower high-frequency textures to avoid readability issues.",
    "メインHomeworkスプライトシート(デスクstatus).300×300 segmentationをmaintainし, center of gravity positionを揃えてください.": "Main Homework sprite sheet (desk status). maintain 300x300 segmentation, align center of gravity.",
    "コーヒーマシンfilmレイヤー. Ontologyとframe・アンカーを揃えるとsense of groundingがoutます.": "Coffee machine film layer. Align ontology and frame/anchor to establish sense of grounding.",
    "Visitor is stillフォールバックportrait 1.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 1. Align design with guest_anim so it looks natural when switching.",
    "Visitor is stillフォールバックportrait 2.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 2. Align design with guest_anim so it looks natural when switching.",
    "Visitor is stillフォールバックportrait 3.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 3. Align design with guest_anim so it looks natural when switching.",
    "Visitor is stillフォールバックportrait 4.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 4. Align design with guest_anim so it looks natural when switching.",
    "Visitor is stillフォールバックportrait 5.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 5. Align design with guest_anim so it looks natural when switching.",
    "Visitor is stillフォールバックportrait 6.対応する guest_anim とデザインを揃えるとWhen switchingにnatureです.": "Visitor fallback portrait 6. Align design with guest_anim so it looks natural when switching.",
    "\"goodきになるかもしれない\"newしいBUYAをrecognizeみ込んでいます……": "Loading new area you might be interested in...",
    "⚠️ 回老家会覆盖当前自定义房间背景（可从 bg-history Restoring historical graphs).\\nAre you sure you want to continue?": "⚠️ Returning home will overwrite current custom background (can be restored from bg-history).\nAre you sure you want to continue?",
    "✅ 已恢复初始底图（局部刷新失败，可手动刷新页面）": "✅ Restored base image (Partial refresh failed, please manually refresh)",
    "⚠️ 将回退到最近一次生成的房间背景，确定继续吗？": "⚠️ Will rollback to latest generated room background, continue?",
    "✅ 已回退到上一次背景（局部刷新失败，可手动刷新页面）": "✅ Rolled back to previous background (Partial refresh failed, please manually refresh)",
    "// 统一使用动态像素角色，避免依赖已删除的 demo static image": "// Use dynamic pixel character to avoid depending on deleted demo static image",
    "エラー発生!アラートエリアへ.": "Error Occurred! Please go to alert area.",
}

with open(r'c:\Users\pc\OneDrive\Desktop\openclaw-hf-space\HuggingClaw-main\frontend\electron-standalone.html', 'r', encoding='utf-8') as f:
    content = f.read()

for k, v in replacements.items():
    content = content.replace(k, v)

with open(r'c:\Users\pc\OneDrive\Desktop\openclaw-hf-space\HuggingClaw-main\frontend\electron-standalone.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("Finished manual fixes!")
